behaviors:
  FoodCollector:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256            # Reduce for faster iterations or memory constraints
      buffer_size: 8192          # Must be multiple of batch_size
      learning_rate: 0.0003      # Slightly increase learning rate if training slow
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5               # More epochs for thorough training per batch
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.95             # Look a bit longer term
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000      